let classes = [
    {
        id: 2310,
        title: "Piano Classes",
        description: "",
        price: 250,
        image: "images/piano.jpeg",
        location: "Music Room 3",
        category: "Music",
        availableInventory: 5,
        rating: 4,
    },
    {
        id: 2311,
        title: "Violin Classes",
        description: "",
        price: 400,
        image: "",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 2312,
        title: "Math Training",
        description: "",
        price: 200,
        image: "",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 2313,
        title: "Swimming Classes",
        description: "",
        price: 1550,
        image: "",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 2314,
        title: "Tennis Classes",
        description: "",
        price: 2700,
        image: "",
        availableInventory: 10,
        rating: 4,
    },
];
